export const FinoLabel={
    loginPageTitle:"LOGIN",
    homePage:"HOME PAGE",
    submit:"SUBMIT",
    loginPageTitle_1:"Sign in to your account",
    forgotPasswordDesc:"Enter Your User Name and Date of Birth, We will send a new Password To your Registered Email Id",
    loginTitle:"WELCOME",
    signUp:"SIGNUP",
    registerAUser:"REGISTER",
    forgotPassword:"Forgot Password?",
    forgotPasswordLabel:"FORGOT PASSWORD",
    dontHaveAnAccount:"Don't Have An Account?",
    createAnAccount:"Create Account",
    userName:"MOBILE NUMBER",
    password:"PASSWORD",
    bankDepositTableHead:[
        {id:"bankTransactionDate",label:"Transaction Date"},
        {id:"recievedFrom",label:"Received From"},
        {id:"collectedBy",label:"Collected By"},
        {id:"collectionAmount",label:"Amount"},
        {id:"onlineAmount",label:"Online Amount"},
        {id:"cashAmount",label:"Cash Amount"},
        {id:"balanceAmount",label:"Balance Amount"},
        {id:"remarks",label:"Remarks"},
    ],
    cmsTransactionTableHead:[
        {id:"cmsTransactionDate",label:"Transaction Date"},
        {id:"recievedFrom",label:"Received From"},
        {id:"collectedBy",label:"Collected By"},
        {id:"collectionAmount",label:"Amount"},
        {id:"onlineAmount",label:"Online Amount"},
        {id:"cashAmount",label:"Cash Amount"},
        {id:"balanceAmount",label:"Balance Amount"},
        {id:"remarks",label:"Remarks"},
    ],
    firstName:"FIRST NAME",
    surname:"LAST NAME",
    dateOfBirth:"DATE OF BIRTH",
    mobileNumber:"MOBILE NUMBER",
    emailID:"EMAIL ID",
    confirmPassword:"CONFIRM PASSWORD",
    finoUserRoles:["USER","ADMIN","MANAGER","CLIENT"],
    userRole:"USER ROLE",
    userDetailsTableHead:[
        {id:"userName",label:"Name Of User"},
        {id:"dateOfBirth",label:"Date Of Birth"},
        {id:"mobileNumber",label:"Mobile Number"},
        {id:"emailId",label:"Email Id"},
        {id:"userRoles",label:"Roles"},
        {id:"isActive",label:"Status"},
    ],
    MonthList:[
        {id:1,month:"JAN",value:"01"},
        {id:2,month:"FEB",value:"02"},
        {id:3,month:"MAR",value:"03"},
        {id:4,month:"APR",value:"04"},
        {id:5,month:"MAY",value:"05"},
        {id:6,month:"JUNE",value:"06"},
        {id:7,month:"JULY",value:"07"},
        {id:8,month:"AUG",value:"08"},
        {id:9,month:"SEPT",value:"09"},
        {id:10,month:"OCT",value:"10"},
        {id:11,month:"NOV",value:"11"},
        {id:12,month:"DEC",value:"12"},
      
      ],
      month:"Month",
      fromDate:"From Date",
      toDate:"To Date",
      date:"Date",
      openingStock:"Opening Stock",
      inwards:"Inwards",
      totalStock:"Total Stock",
      totalSales:"Total Sales",
      closingStock:"Closing Stock",
      dipStock:"Dip Stock",
      variation:"Variation",
      dipStockInCms:"Dip Stock(CM's)",
      dipStockLtrs:"Dip Stock(LTR's)",
      testing:"Testing",
      density:"Density",
      waterDip:"Water Dip",
      remarks:"Remarks",
      openingMeter:"Opening Meter",
      sales:"Sales(Ltr's)",
      totalMeterSales:"Total Meter Sales(LTR's)"










}