export const FinoLabel={
    loginPageTitle:"LOGIN",
    homePage:"HOME PAGE",
    submit:"SUBMIT",
    loginPageTitle_1:"Sign in to your account",
    forgotPasswordDesc:"Enter Your User Name and Date of Birth, We will send a new Password To your Registered Email Id.",
    resetPasswordDesc:"Please enter your old password and new password to reset your current password.",
    updateUserDesc:"Please enter Below Details to update user.....",
    loginTitle:"WELCOME",
    signUp:"SIGNUP",
    registerAUser:"REGISTER",
    forgotPassword:"Forgot Password?",
    forgotPasswordLabel:"FORGOT PASSWORD",
    dontHaveAnAccount:"Don't Have An Account?",
    createAnAccount:"Create Account",
    userName:"MOBILE NUMBER",
    password:"PASSWORD",
    bankDepositTableHead:[
        {id:"bankTransactionDate",label:"Transaction Date"},
        {id:"depositedInBank",label:"Deposited Bank"},
        {id:"depositedBy",label:"Deposited By"},
        {id:"collectionAmount",label:"Amount"},
        {id:"cashAmount",label:"Cash Amount"},
        {id:"remarks",label:"Remarks"},
    ],
    cmsTransactionTableHead:[
        {id:"cmsTransactionDate",label:"Transaction Date"},
        {id:"recievedFrom",label:"Received From"},
        {id:"collectedBy",label:"Collected By"},
        {id:"collectionAmount",label:"Amount"},
        {id:"onlineAmount",label:"Online Amount"},
        {id:"cashAmount",label:"Cash Amount"},
        {id:"balanceAmount",label:"Balance Amount"},
        {id:"remarks",label:"Remarks"},
    ],
    firstName:"FIRST NAME",
    surname:"LAST NAME",
    dateOfBirth:"DATE OF BIRTH",
    mobileNumber:"MOBILE NUMBER",
    emailID:"EMAIL ID",
    confirmPassword:"CONFIRM PASSWORD",
    oldPassword:"OLD PASSWORD",
    newPassword:"NEW PASSWORD",
    finoUserRoles:["USER","ADMIN","MANAGER","CLIENT"],
    userRole:"USER ROLE",
    userDetailsTableHead:[
        {id:"userName",label:"Name Of User"},
        {id:"dateOfBirth",label:"Date Of Birth"},
        {id:"mobileNumber",label:"Mobile Number"},
        {id:"emailId",label:"Email Id"},
        {id:"userRoles",label:"Roles"},
        {id:"isActive",label:"Status"},
    ],
    MonthList:[
        {id:1,month:"JAN",value:"01"},
        {id:2,month:"FEB",value:"02"},
        {id:3,month:"MAR",value:"03"},
        {id:4,month:"APR",value:"04"},
        {id:5,month:"MAY",value:"05"},
        {id:6,month:"JUNE",value:"06"},
        {id:7,month:"JULY",value:"07"},
        {id:8,month:"AUG",value:"08"},
        {id:9,month:"SEPT",value:"09"},
        {id:10,month:"OCT",value:"10"},
        {id:11,month:"NOV",value:"11"},
        {id:12,month:"DEC",value:"12"},
      
      ],
      month:"Month",
      fromDate:"From Date",
      toDate:"To Date",
      date:"Date",
      openingStock:"Opening Stock",
      inwards:"Inwards",
      totalStock:"Total Stock",
      totalSales:"Total Sales",
      closingStock:"Closing Stock",
      dipStock:"Dip Stock",
      variation:"Variation",
      dipStockInCms:"Dip Stock(CM's)",
      dipStockLtrs:"Dip Stock(LTR's)",
      testing:"Testing",
      density:"Density",
      waterDip:"Water Dip",
      remarks:"Remarks",
      openingMeter:"Opening Meter",
      closingMeter:"Closing Meter",
      sales:"Sales(Ltr's)",
      totalMeterSales:"Total Meter Sales(LTR's)",
noRecordFound:"NO RECORD FOUND FOR :- ",
alertDescription:"No information is available for the given  field's in our database.....",
tableAlertDescriptionForReciept:"No Reciept information is available for the given sales in our database.....",
tableNoRecordFound:"NO RECORD FOUND.... !! ",
noRecordFoundAlert:"NO RECORD FOUND.......",
noRecordFoundDesc:"No information is available  in our database at the moment.....",
msSaleFilteredRow:[
    {id:"date",label:"Date"},
    {id:"openingStock",label:"Opening Stock"},
    {id:"inwards",label:"Inwards"},
    {id:"totalStock",label:"Total Sales"},
    {id:"totalSales",label:"Opening Stock"},
    {id:"closingStock",label:"Closing Stock"},
    {id:"dipStock",label:"Dip Stock"},
    {id:"variation",label:"Variation"},
    {id:"dipStockInCms",label:"Dip Stock(CM's)"},
    {id:"dipStockLtrs",label:"Dip Stock(LTR's)"},
    {id:"totalMeterSales",label:"Total Meter Sales(LTR's)"},
    {id:"testing",label:"Testing"},
    {id:"density",label:"Density"},
    {id:"waterDip",label:"Water Dip"},
    {id:"remarks",label:"remarks"},
],
clientTableHead:[
    {id:"clientId",label:"Client Id"},
    {id:"clientName",label:"Client Name"},
  ],

  bankTableHead:[
    {id:"clientId",label:"Bank Id"},
    {id:"bankName",label:"BankName Name"},
  ],









}