export const FuelReportExcelHead = {

    msSaleExcelHead: [
        { id: "msSaleDate", label: "Date" },
        { id: "openingStockOfMSSale", label: "Opening Stock" },
        { id: "inwardOfMSSale", label: "Inwards" },
        { id: "totalStockMSSale", label: "Total Stock" },
        { id: "totalSalesMSSale", label: "Total Sales" },
        { id: "closingStockMSSale", label: "Closing Stock" },
        { id: "dipStockOfMSSale", label: "Dip Stock" },
        { id: "variationOfMSSale", label: "Variation" },
        { id: "dipStockOfMSSaleInCentimeter", label: "Dip Stock(CM's)" },
        { id: "dipStockOfMSSaleInLtrs", label: "Dip Stock(LTR's)" },
        { id: "openingMeterOfMSSaleNozzleOne", label: "Opening Meter of N1" },
        { id: "salesForMSSaleNozzleOne", label: "Sales  of N1" },
        { id: "openingMeterOfMSSaleNozzleTwo", label: "Opening Meter  of N2" },
        { id: "salesForMSSaleNozzleTwo", label: "Sales  of N2" },
        { id: "totalMeterSalesForTheDayForMSSaleInLtrs", label: "Total Meter Sales(LTR's)" },
        { id: "testing", label: "Testing" },
        { id: "density", label: "Density" },
        { id: "waterDip", label: "Water Dip" },
        { id: "remarks", label: "remarks" },
    ],
    hsdTankOneExcelHead: [
        { id: "hsdTankOneDate", label: "Date" },
        { id: "openingStockOfHsdTankOne", label: "Opening Stock" },
        { id: "inwardOfHsdTankOne", label: "Inwards" },
        { id: "totalStockHsdTankOne", label: "Total Stock" },
        { id: "totalSalesHsdTankOne", label: "Total Sales" },
        { id: "closingStockHsdTankOne", label: "Closing Stock" },
        { id: "dipStockOfHsdTankOne", label: "Dip Stock" },
        { id: "variationOfHsdTankOne", label: "Variation" },
        { id: "dipOfHsdTankOneInCentimeter", label: "Dip Stock(CM's)" },
        { id: "dipOfHsdTankOneInLtrs", label: "Dip Stock(LTR's)" },

        { id: "openingMeterOfHsdTankOneNozzleOne", label: "Opening Meter  of N1" },
        { id: "salesForHsdTankOneNozzleOne", label: "Sales  of N1" },
        { id: "openingMeterOfHsdTankOneNozzleTwo", label: "Opening Meter  of N2" },
        { id: "salesForHsdTankOneNozzleTwo", label: "Sales of N2" },
        { id: "totalSalesMpdOne", label: "Total Sales(MPD-01)" },
        { id: "openingMeterOfHsdTankOneNozzleThree", label: "Opening Meter of N3" },
        { id: "salesForHsdTankOneNozzleThree", label: "Sales of N3" },
        { id: "openingMeterOfHsdTankOneNozzleFour", label: "Opening Meter of N4" },
        { id: "salesForHsdTankOneNozzleFour", label: "Sales of N4" },
        { id: "totalSalesMpdTwo", label: "Total Sales(MPD-02)" },

        { id: "totalSalesForTheDayHsdTankOne", label: "Total Meter Sales(LTR's)" },
        { id: "testing", label: "Testing" },
        { id: "density", label: "Density" },
        { id: "waterDip", label: "Water Dip" },
        { id: "remarks", label: "remarks" },
    ],
    hsdTankTwoExcelHead: [
        { id: "hsdTankTwoDate", label: "Date" },
        { id: "openingStockOfHsdTankTwo", label: "Opening Stock" },
        { id: "inwardOfHsdTankTwo", label: "Inwards" },
        { id: "totalStockHsdTankTwo", label: "Total Stock" },
        { id: "totalSalesHsdTankTwo", label: "Total Sales" },
        { id: "closingStockHsdTankTwo", label: "Closing Stock" },
        { id: "dipStockOfHsdTankTwo", label: "Dip Stock" },
        { id: "variationOfHsdTankTwo", label: "Variation" },
        { id: "dipOfHsdTankTwoInCentimeter", label: "Dip Stock(CM's)" },
        { id: "dipOfHsdTankTwoInLtrs", label: "Dip Stock(LTR's)" },

        { id: "openingMeterOfHsdTankTwoNozzleOne", label: "Opening Meter of N1" },
        { id: "salesForHsdTankTwoNozzleOne", label: "Sales of N1" },
        { id: "openingMeterOfHsdTankTwoNozzleTwo", label: "Opening Meter of N2" },
        { id: "salesForHsdTankTwoNozzleTwo", label: "Sales of N2" },


        { id: "totalSalesForTheDayHsdTankTwo", label: "Total Meter Sales(LTR's)" },
        { id: "testing", label: "Testing" },
        { id: "density", label: "Density" },
        { id: "waterDip", label: "Water Dip" },
        { id: "remarks", label: "remarks" },
    ]
}

